// Generated by gencpp from file velocity_control/event.msg
// DO NOT EDIT!


#ifndef VELOCITY_CONTROL_MESSAGE_EVENT_H
#define VELOCITY_CONTROL_MESSAGE_EVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace velocity_control
{
template <class ContainerAllocator>
struct event_
{
  typedef event_<ContainerAllocator> Type;

  event_()
    : event()  {
    }
  event_(const ContainerAllocator& _alloc)
    : event(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type;
  _event_type event;




  typedef boost::shared_ptr< ::velocity_control::event_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::velocity_control::event_<ContainerAllocator> const> ConstPtr;

}; // struct event_

typedef ::velocity_control::event_<std::allocator<void> > event;

typedef boost::shared_ptr< ::velocity_control::event > eventPtr;
typedef boost::shared_ptr< ::velocity_control::event const> eventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::velocity_control::event_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::velocity_control::event_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace velocity_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'velocity_control': ['/home/rlalleme/ros/indigo/src/template_modules/velocity_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::velocity_control::event_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::velocity_control::event_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velocity_control::event_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velocity_control::event_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velocity_control::event_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velocity_control::event_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::velocity_control::event_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aea470b1ed54075e83032ee4be16538";
  }

  static const char* value(const ::velocity_control::event_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aea470b1ed54075ULL;
  static const uint64_t static_value2 = 0xe83032ee4be16538ULL;
};

template<class ContainerAllocator>
struct DataType< ::velocity_control::event_<ContainerAllocator> >
{
  static const char* value()
  {
    return "velocity_control/event";
  }

  static const char* value(const ::velocity_control::event_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::velocity_control::event_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string event\n\
";
  }

  static const char* value(const ::velocity_control::event_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::velocity_control::event_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct event_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::velocity_control::event_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::velocity_control::event_<ContainerAllocator>& v)
  {
    s << indent << "event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VELOCITY_CONTROL_MESSAGE_EVENT_H
